=== Citizen-Cane/teaselib/src/teaselib/core/items.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Items (Toys,Household,Clothes,Accessoires,Gadgets)*>
<!ELEMENT Toys (Item)*>
<!ELEMENT Household (Item)*>
<!ELEMENT Clothes (Item)*>
<!ELEMENT Shoes (Item)*>
<!ELEMENT Bondage (Item)*>
<!ELEMENT Accessoires (Item)*>
<!ELEMENT Gadgets (Item)*>
<!ELEMENT Item (Attribute)*>
<!ELEMENT Item (DefaultPeer)*>
<!ELEMENT Item (BlockedBy)*>
<!ATTLIST Item 
	item CDATA #REQUIRED
	guid CDATA #REQUIRED
	displayName CDATA #REQUIRED
>
<!ELEMENT Attribute (#PCDATA)>

=== Citizen-Cane/teaselib/src.test/teaselib/test/useritems.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Items SYSTEM "items.dtd">

<!-- item defaults - defines default item set in TeaseLib -->
<Items>
	<Toys>
		<Item item="Humbler" guid="humbler" displayName="My Humbler">
			<Attribute> Material.Wood </Attribute>
			<Attribute> Features.Lockable </Attribute>
			<Attribute> Sexuality.Sex.Male </Attribute>
		</Item>

		<Item item="Wrist_Restraints" guid="wrist_restraints" displayName="Wrist Restraints">
			<Attribute> Material.Leather </Attribute>
		</Item>

		<Item item="Wrist_Restraints" guid="handcuffs" displayName="Hand cuffs">
			<Attribute> Material.Metal </Attribute>
		</Item>
		
	</Toys>

	<Household>
		<Item item="Wooden_Spoon" guid="wooden_spoon" displayName="Wooden spoon">
			<Attribute> Material.Wood </Attribute>
		</Item>
	</Household>
	
	<Clothes>
		<Item item="Catsuit" guid="catsuit" displayName="Catsuit">
			<Attribute> Material.Rubber </Attribute>
		</Item>
	</Clothes>

	<Gadgets>
		<Item item="EStim_Controller" guid="estim_controller" displayName="EStim-Test-Entry">
		</Item>
	</Gadgets>
</Items>

=== Citizen-Cane/teaselib/src.test/teaselib/core/UserItems.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Items SYSTEM "items.dtd">

<!-- item defaults - defines default item set in TeaseLib -->
<Items>
	<Toys>
		<Item item="Humbler" guid="myHumbler" displayName="My Humbler" available="true">
			<Attribute> Material.Wood </Attribute>
			<Attribute> Features.Lockable </Attribute>
		</Item>
	</Toys>

	<Household>
		<Item item="Wooden_Spoon" guid="wooden_spoon" displayName="Wooden spoon" available="false">
			<Attribute> Material.Wood </Attribute>
		</Item>
	</Household>
	
	<Clothes>
		<Item item="Catsuit" guid="catsuit" displayName="Catsuit" available="true">
			<Attribute> Material.Rubber </Attribute>
		</Item>
	</Clothes>

	<Gadgets>
		<Item item="Computer_Controlled_EStim" guid="estim" displayName="EStim" available="false">
		</Item>
	</Gadgets>
</Items>

=== Citizen-Cane/teaselib/src/teaselib/hosts/sexscripts_useritems.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Items SYSTEM "items.dtd">

<!-- SexScripts non-generic user items - not covered by TeaseLib default items -->

<Items>
	<Toys>
		<Item item="Buttplug" guid="inflatable_buttplug" displayName="Inflatable buttplug">
			<Attribute> Toys.Anal.Plug </Attribute>
			<Attribute> Body.Orifice.Anal </Attribute>
			<Attribute> Features.Inflatable </Attribute>
		</Item>
		<Item item="Buttplug" guid="vibrating_buttplug" displayName="Vibrating buttplug">
			<Attribute> Toys.Anal.Plug </Attribute>
			<Attribute> Body.Orifice.Anal </Attribute>
			<Attribute> Features.Vibrating </Attribute>
		</Item>
		<Item item="Dildo" guid="vibrating_dildo" displayName="Vibrating dildo">
			<Attribute> Features.Vibrating </Attribute>
		</Item>

		<Item item="Ankle_Restraints" guid="ankle_cuffs" displayName="Ankle cuffs">
			<Attribute> Features.Lockable </Attribute>
			<Attribute> Material.Metal </Attribute>
		</Item>

		<Item item="Wrist_Restraints" guid="handcuffs" displayName="Hand cuffs">
			<Attribute> Features.Lockable </Attribute>
			<Attribute> Material.Metal </Attribute>
		</Item>

		<Item item="Plants" guid="plants" displayName="Plants">
		</Item>
	</Toys>

	<Household>
	</Household>
	
	<Clothes>
		<Item item="Dress" guid="maid_attire" displayName="Maid attire">
		</Item>

		<Item item="Jewelry" guid="jewelry" displayName="Jewelry">
		</Item>
	</Clothes>

	<Gadgets>
	</Gadgets>
</Items>

=== Citizen-Cane/teaselib/defaults/items.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Items SYSTEM "items.dtd">

<!--item defaults - defines default item set in TeaseLib -->

<Items>
	<Toys>
		<Item item="Humbler" guid="humbler" displayName="Humbler">
		</Item>
	</Toys>

	<Household>
		<Item item="Wooden_Spoon" guid="wooden_spoon" displayName="Woodenspoon">
			<Attribute> Material.Wood </Attribute>
		</Item>
	</Household>
	
	<Clothes>
		<Item item="Catsuit" guid="catsuit" displayName="Catsuit">
		</Item>
	</Clothes>

	<Gadgets>
		<Item item="Computer_Controlled_EStim" guid="estim" displayName="Teaselib-enabled estim controller">
		</Item>
	</Gadgets>
</Items>

=== Citizen-Cane/teaselib/src.test.tools/teaselib/test/useritems2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Items SYSTEM "items.dtd">

<!-- item defaults - defines default item set in TeaseLib -->
<Items>
	<Toys>
		<Item item="Humbler" guid="my_humbler" displayName="My Humbler">
			<Attribute>Material.Metal</Attribute>
			<Attribute> Features.Lockable </Attribute>
			<Attribute> Sexuality.Sex.Male </Attribute>
		</Item>

		<Item item="Dildo" guid="another_dildo" displayName="Another Dildo">
			<Attribute>Material.Rubber</Attribute>
		</Item>
	</Toys>
</Items>
